[03.09.2024, 14:40:42] RequestError: Error: read ECONNRESET
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[04.09.2024, 06:13:38] Error: ETELEGRAM: 502 Bad Gateway
    at C:\web\chat-bot-telegram\node_modules\node-telegram-bot-api\src\telegram.js:316:15
    at tryCatcher (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
[04.09.2024, 06:13:39] Error: ETELEGRAM: 502 Bad Gateway
    at C:\web\chat-bot-telegram\node_modules\node-telegram-bot-api\src\telegram.js:316:15
    at tryCatcher (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
[04.09.2024, 06:13:39] Error: ETELEGRAM: 502 Bad Gateway
    at C:\web\chat-bot-telegram\node_modules\node-telegram-bot-api\src\telegram.js:316:15
    at tryCatcher (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
[04.09.2024, 06:13:40] Error: ETELEGRAM: 502 Bad Gateway
    at C:\web\chat-bot-telegram\node_modules\node-telegram-bot-api\src\telegram.js:316:15
    at tryCatcher (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
[04.09.2024, 06:13:40] Error: ETELEGRAM: 502 Bad Gateway
    at C:\web\chat-bot-telegram\node_modules\node-telegram-bot-api\src\telegram.js:316:15
    at tryCatcher (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
[04.09.2024, 11:36:02] ReferenceError: startMessage is not defined
    at startCommand (file:///C:/web/chat-bot-telegram/src/telegram-bot/commands/start.js:8:3)
    at async Object.callback (file:///C:/web/chat-bot-telegram/src/telegram-bot/telegramBot.js:15:5)
[04.09.2024, 12:10:58] Error: ETELEGRAM: 502 Bad Gateway
    at C:\web\chat-bot-telegram\node_modules\node-telegram-bot-api\src\telegram.js:316:15
    at tryCatcher (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
[04.09.2024, 12:10:59] Error: ETELEGRAM: 502 Bad Gateway
    at C:\web\chat-bot-telegram\node_modules\node-telegram-bot-api\src\telegram.js:316:15
    at tryCatcher (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
[04.09.2024, 12:10:59] Error: ETELEGRAM: 502 Bad Gateway
    at C:\web\chat-bot-telegram\node_modules\node-telegram-bot-api\src\telegram.js:316:15
    at tryCatcher (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
[04.09.2024, 12:10:59] Error: ETELEGRAM: 502 Bad Gateway
    at C:\web\chat-bot-telegram\node_modules\node-telegram-bot-api\src\telegram.js:316:15
    at tryCatcher (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
[04.09.2024, 12:11:00] Error: ETELEGRAM: 502 Bad Gateway
    at C:\web\chat-bot-telegram\node_modules\node-telegram-bot-api\src\telegram.js:316:15
    at tryCatcher (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
[05.09.2024, 06:12:46] Error: ETELEGRAM: 502 Bad Gateway
    at C:\web\chat-bot-telegram\node_modules\node-telegram-bot-api\src\telegram.js:316:15
    at tryCatcher (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
[05.09.2024, 06:12:46] Error: ETELEGRAM: 502 Bad Gateway
    at C:\web\chat-bot-telegram\node_modules\node-telegram-bot-api\src\telegram.js:316:15
    at tryCatcher (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
[05.09.2024, 06:12:47] Error: ETELEGRAM: 502 Bad Gateway
    at C:\web\chat-bot-telegram\node_modules\node-telegram-bot-api\src\telegram.js:316:15
    at tryCatcher (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
[05.09.2024, 06:12:47] Error: ETELEGRAM: 502 Bad Gateway
    at C:\web\chat-bot-telegram\node_modules\node-telegram-bot-api\src\telegram.js:316:15
    at tryCatcher (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
[05.09.2024, 09:23:32] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[05.09.2024, 09:23:45] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[05.09.2024, 16:29:21] ReferenceError: fetchData is not defined
    at file:///C:/web/chat-bot-telegram/src/server.js:73:1
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)
[06.09.2024, 06:12:11] Error: ETELEGRAM: 502 Bad Gateway
    at C:\web\chat-bot-telegram\node_modules\node-telegram-bot-api\src\telegram.js:316:15
    at tryCatcher (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
[06.09.2024, 06:12:11] Error: ETELEGRAM: 502 Bad Gateway
    at C:\web\chat-bot-telegram\node_modules\node-telegram-bot-api\src\telegram.js:316:15
    at tryCatcher (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
[06.09.2024, 06:12:12] Error: ETELEGRAM: 502 Bad Gateway
    at C:\web\chat-bot-telegram\node_modules\node-telegram-bot-api\src\telegram.js:316:15
    at tryCatcher (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
[06.09.2024, 06:12:12] Error: ETELEGRAM: 502 Bad Gateway
    at C:\web\chat-bot-telegram\node_modules\node-telegram-bot-api\src\telegram.js:316:15
    at tryCatcher (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
[06.09.2024, 06:12:13] Error: ETELEGRAM: 502 Bad Gateway
    at C:\web\chat-bot-telegram\node_modules\node-telegram-bot-api\src\telegram.js:316:15
    at tryCatcher (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
[06.09.2024, 06:12:13] Error: ETELEGRAM: 502 Bad Gateway
    at C:\web\chat-bot-telegram\node_modules\node-telegram-bot-api\src\telegram.js:316:15
    at tryCatcher (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
[06.09.2024, 08:15:12] ReferenceError: fetchData is not defined
    at file:///C:/web/chat-bot-telegram/src/server.js:73:1
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)
[06.09.2024, 09:21:50] Error: ETELEGRAM: 400 Bad Request: query is too old and response timeout expired or query ID is invalid
    at C:\web\chat-bot-telegram\node_modules\node-telegram-bot-api\src\telegram.js:316:15
    at tryCatcher (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
[06.09.2024, 09:21:50] Error: ETELEGRAM: 400 Bad Request: query is too old and response timeout expired or query ID is invalid
    at C:\web\chat-bot-telegram\node_modules\node-telegram-bot-api\src\telegram.js:316:15
    at tryCatcher (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
[06.09.2024, 09:42:13] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[06.09.2024, 09:42:26] Error: ETELEGRAM: 400 Bad Request: query is too old and response timeout expired or query ID is invalid
    at C:\web\chat-bot-telegram\node_modules\node-telegram-bot-api\src\telegram.js:316:15
    at tryCatcher (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
[06.09.2024, 12:10:58] ReferenceError: Cannot access 'temperatures' before initialization
    at generateTablePechVr (file:///C:/web/chat-bot-telegram/src/telegram-bot/generates/pechVr/generatetable.js:30:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[06.09.2024, 12:14:32] ReferenceError: getLastTimestamp is not defined
    at generateTablePechVr (file:///C:/web/chat-bot-telegram/src/telegram-bot/generates/pechVr/generatetable.js:13:25)
    at handleCallbackQuery (file:///C:/web/chat-bot-telegram/src/telegram-bot/buttons/callbackQueryHandler.js:20:21)
[06.09.2024, 12:15:25] ReferenceError: getLastTimestamp is not defined
    at generateTablePechVr (file:///C:/web/chat-bot-telegram/src/telegram-bot/generates/pechVr/generatetable.js:13:25)
    at handleCallbackQuery (file:///C:/web/chat-bot-telegram/src/telegram-bot/buttons/callbackQueryHandler.js:20:21)
[06.09.2024, 18:45:57] RequestError: Error: read ECONNRESET
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[06.09.2024, 20:10:29] RequestError: Error: read ECONNRESET
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[07.09.2024, 06:11:37] Error: ETELEGRAM: 429 Too Many Requests: retry after 5
    at C:\web\chat-bot-telegram\node_modules\node-telegram-bot-api\src\telegram.js:316:15
    at tryCatcher (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
[07.09.2024, 06:11:38] Error: ETELEGRAM: 429 Too Many Requests: retry after 5
    at C:\web\chat-bot-telegram\node_modules\node-telegram-bot-api\src\telegram.js:316:15
    at tryCatcher (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
[07.09.2024, 06:11:38] Error: ETELEGRAM: 429 Too Many Requests: retry after 5
    at C:\web\chat-bot-telegram\node_modules\node-telegram-bot-api\src\telegram.js:316:15
    at tryCatcher (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
[07.09.2024, 06:11:39] Error: ETELEGRAM: 502 Bad Gateway
    at C:\web\chat-bot-telegram\node_modules\node-telegram-bot-api\src\telegram.js:316:15
    at tryCatcher (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
[07.09.2024, 06:11:40] Error: ETELEGRAM: 502 Bad Gateway
    at C:\web\chat-bot-telegram\node_modules\node-telegram-bot-api\src\telegram.js:316:15
    at tryCatcher (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
[07.09.2024, 06:11:40] Error: ETELEGRAM: 502 Bad Gateway
    at C:\web\chat-bot-telegram\node_modules\node-telegram-bot-api\src\telegram.js:316:15
    at tryCatcher (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
[07.09.2024, 06:11:41] Error: ETELEGRAM: 502 Bad Gateway
    at C:\web\chat-bot-telegram\node_modules\node-telegram-bot-api\src\telegram.js:316:15
    at tryCatcher (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
[07.09.2024, 06:11:41] Error: ETELEGRAM: 502 Bad Gateway
    at C:\web\chat-bot-telegram\node_modules\node-telegram-bot-api\src\telegram.js:316:15
    at tryCatcher (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
[07.09.2024, 12:08:40] RequestError: Error: read ECONNRESET
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 00:11:53] RequestError: Error: connect ETIMEDOUT 149.154.167.220:443
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 00:12:14] RequestError: Error: connect ETIMEDOUT 149.154.167.220:443
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 06:11:16] Error: ETELEGRAM: 502 Bad Gateway
    at C:\web\chat-bot-telegram\node_modules\node-telegram-bot-api\src\telegram.js:316:15
    at tryCatcher (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
[08.09.2024, 06:11:16] Error: ETELEGRAM: 502 Bad Gateway
    at C:\web\chat-bot-telegram\node_modules\node-telegram-bot-api\src\telegram.js:316:15
    at tryCatcher (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
[08.09.2024, 06:11:16] Error: ETELEGRAM: 502 Bad Gateway
    at C:\web\chat-bot-telegram\node_modules\node-telegram-bot-api\src\telegram.js:316:15
    at tryCatcher (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
[08.09.2024, 06:11:17] Error: ETELEGRAM: 502 Bad Gateway
    at C:\web\chat-bot-telegram\node_modules\node-telegram-bot-api\src\telegram.js:316:15
    at tryCatcher (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
[08.09.2024, 06:11:17] Error: ETELEGRAM: 502 Bad Gateway
    at C:\web\chat-bot-telegram\node_modules\node-telegram-bot-api\src\telegram.js:316:15
    at tryCatcher (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\web\chat-bot-telegram\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
[08.09.2024, 08:04:03] RequestError: Error: read ECONNRESET
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:04:14] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:04:25] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:04:38] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:04:50] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:04:50] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:04:51] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:04:51] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:04:51] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:04:52] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:04:52] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:04:52] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:04:53] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:04:53] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:04:53] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:04:54] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:04:54] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:04:54] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:04:55] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:04:55] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:04:55] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:04:56] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:04:56] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:04:56] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:04:56] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:04:57] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:04:57] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:02] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:03] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:03] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:03] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:04] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:04] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:04] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:05] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:05] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:05] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:06] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:06] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:06] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:07] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:07] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:07] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:15] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:15] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:15] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:16] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:16] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:16] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:17] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:17] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:17] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:18] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:18] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:18] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:19] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:19] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:19] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:20] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:27] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:27] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:28] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:28] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:28] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:29] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:29] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:29] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:30] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:30] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:30] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:31] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:31] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:31] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:32] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:32] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[08.09.2024, 08:05:40] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[09.09.2024, 01:13:12] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[09.09.2024, 01:13:23] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[09.09.2024, 19:14:42] RequestError: Error: connect ECONNABORTED 149.154.167.220:443
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[09.09.2024, 19:14:54] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[09.09.2024, 19:15:07] RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[10.09.2024, 13:47:35] ReferenceError: loadingMessage is not defined
    at handleTextMessage (file:///C:/web/chat-bot-telegram/src/telegram-bot/buttons/handleTextMessage.js:108:39)
    at async handleMessage (file:///C:/web/chat-bot-telegram/src/telegram-bot/handlers/message.js:17:3)
[10.09.2024, 13:49:41] ReferenceError: loadingMessage is not defined
    at handleTextMessage (file:///C:/web/chat-bot-telegram/src/telegram-bot/buttons/handleTextMessage.js:109:7)
    at async handleMessage (file:///C:/web/chat-bot-telegram/src/telegram-bot/handlers/message.js:17:3)
[11.09.2024, 01:51:37] RequestError: Error: read ECONNRESET
    at new RequestError (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\web\chat-bot-telegram\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (C:\web\chat-bot-telegram\node_modules\@cypress\request\request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
